/* global window */
// Shared data for the mobile Mimir prototype. Mirrors LibraryBrowser.jsx so
// the mobile experience reads the exact same lore — but lives under window.MM_
// so it can't collide with the desktop kit when both are loaded.

const MM_TYPE_COLOR = {
  Character: "#d99366",
  Place:     "#7da265",
  Faction:   "#c43a4e",
  Culture:   "#a07cc8",
  Event:     "#8d8478",
  Language:  "#8aa0ab",
  Spell:     "#6b89c2",
  Rune:      "#c9a227",
  Artefact:  "#a8814d",
};

const MM_ENTRIES = [
  { id: "sigrun", filter: "characters", type: "Character",
    name: "Sigrun Ulfsdottir", faction: "Iron Crown",
    aliases: "'The Iron-Crown' · 'Wolf of Kernow'",
    snippet: "Daughter of Ulf, jarl of Caernarfon. She took the oath at fifteen and the crown at twenty-three, after her father fell at the burning of Hellas.",
    thumb: "../../../assets/characters/spearmaiden.png",
    status: "stub", links: 12, edited: "2 days ago" },
  { id: "ulf", filter: "characters", type: "Character",
    name: "Ulf the Wolf-Father", faction: "Iron Crown",
    aliases: "Ulf jarl Caernarfon · 'Wolf-Father'",
    snippet: "Founder of the Iron Crown confederation. Fell at the burning of Hellas in the third winter of the long war. Father of Sigrun.",
    thumb: "../../../assets/characters/huskarl.png",
    status: "complete", links: 23, edited: "5 days ago" },
  { id: "kernow-king", filter: "characters", type: "Character",
    name: "Bran ap Cadwy", faction: "Kingdom of Kernow",
    aliases: "The Stone-King · Bran of the Twelve Towers",
    snippet: "King of Kernow at the time of the landing. A scholar before he was a king. Resisted the call to war until the third dawn of the siege.",
    thumb: "../../../assets/characters/kernow-king.png",
    status: "draft", links: 18, edited: "1 week ago" },
  { id: "spearmaiden", filter: "characters", type: "Character",
    name: "Astrid Half-Hand", faction: "Iron Crown",
    aliases: "Astrid skjaldmaer",
    snippet: "Sigrun's shield-sister and second. Lost two fingers at the breaking of the Avalon ice. Refuses a bow, fights only with the spear.",
    thumb: "../../../assets/characters/raider.png",
    status: "stub", links: 8, edited: "today" },
  { id: "young-raider", filter: "characters", type: "Character",
    name: "Hakon the Quiet", faction: "Iron Crown",
    aliases: null,
    snippet: "A boy of fourteen winters when Sigrun took him from the smoke of his village. He has not spoken since, but he hears every word said in the hall.",
    thumb: "../../../assets/characters/young-raider.png",
    status: "stub", links: 4, edited: "yesterday" },
  { id: "bear", filter: "characters", type: "Character",
    name: "The Bear of Hornfolke", faction: "Hornfolke",
    aliases: "Skall — the brown one",
    snippet: "An ancestor-spirit who walks the high passes in the form of a great brown bear. Said to demand a name in trade for safe passage.",
    thumb: "../../../assets/characters/bear.png",
    status: "draft", links: 7, edited: "3 days ago" },

  { id: "caernarfon", filter: "places", type: "Place",
    name: "Caernarfon", faction: "Kingdom — seat of the Iron Crown",
    aliases: "Caer-na-Carn · 'The Hall on the Fjord'",
    snippet: "The longhall and stone-keep at the head of the Caernarfon estuary. Seat of Ulf, then Sigrun. Twelve hearths, three rune-walls, one well that has never frozen.",
    thumb: "../../../assets/plates/kernow.png",
    status: "complete", links: 19, edited: "today" },
  { id: "alba", filter: "places", type: "Place",
    name: "Alba", faction: "Highland kingdoms",
    aliases: "The High Country · The North-Above",
    snippet: "The mountain country north of the wall, where the winter kings still keep the old fires. Few roads, fewer welcomes. A place that remembers names longer than people do.",
    thumb: "../../../assets/plates/alba.png",
    status: "draft", links: 11, edited: "4 days ago" },
  { id: "yggdrasil", filter: "places", type: "Place",
    name: "Yggdrasil", faction: "Cosmic — the world-tree",
    aliases: "The Ash · The World-Spine",
    snippet: "The great ash that grew from the seed Odin planted in Niflheimr. Its roots span the Ginnungagap; four worlds were shaped from the fruit it bore on the first dawn.",
    thumb: "../../../assets/plates/forest.png",
    status: "stub", links: 34, edited: "1 week ago" },
  { id: "hellas", filter: "places", type: "Place",
    name: "Hellas", faction: "Ruined city — Empire of the South",
    aliases: "The Burning · 'The Ash-Coast'",
    snippet: "Once the brightest of the southern cities, now a salt-glass ruin. Burned in the third winter of the long war. Ulf the Wolf-Father fell within its harbour walls.",
    thumb: "../../../assets/plates/hellas.png",
    status: "draft", links: 16, edited: "5 days ago" },

  { id: "iron-crown", filter: "factions", type: "Faction",
    name: "The Iron Crown", faction: "Confederation of jarldoms",
    aliases: "Járnkróna · 'The Wolf-Banner'",
    snippet: "The confederation Ulf bound together with seven oaths and a circle of black iron. Sigrun wears the crown now; the oaths still hold, though three of the seven jarls are dead.",
    thumb: "../../../assets/plates/hornfolke.png",
    status: "complete", links: 27, edited: "today" },
  { id: "asgardr", filter: "factions", type: "Faction",
    name: "Ásgarðr", faction: "Clan of the Aesir",
    aliases: "The Asgardians · 'The Hall-Above'",
    snippet: "The hall of the Aesir, seated above Midgard on the high branch of Yggdrasil. Odin sits at its head; Frigg keeps its threshold; Thor its outer wall.",
    thumb: "../../../assets/plates/empire.png",
    status: "stub", links: 41, edited: "2 days ago" },
  { id: "kernow", filter: "factions", type: "Faction",
    name: "Kingdom of Kernow", faction: "Old kingdom of the south",
    aliases: "The Stone-Kingdom · Cair-now",
    snippet: "The oldest standing kingdom on the southern coast. Ruled from twelve towers. Refused the Iron Crown's hand twice; signed the Treaty of Avalon at the third asking.",
    thumb: "../../../assets/plates/dumnonia.png",
    status: "draft", links: 14, edited: "6 days ago" },

  { id: "hornfolke", filter: "cultures", type: "Culture",
    name: "The Hornfolke", faction: "Northmen of the petty kingdoms",
    aliases: "The Northmen · 'The Horn-Wearers'",
    snippet: "Tribal kingdoms of the long northern coast. They reckon the year by frosts, not by months. Their oaths are sworn on iron and remembered in ash.",
    thumb: "../../../assets/plates/hornfolke.png",
    status: "complete", links: 22, edited: "today" },
  { id: "winter-kings", filter: "cultures", type: "Culture",
    name: "The Winter Kings", faction: "Highlanders of Alba",
    aliases: "Konunga vetrar · 'The Old Crowns'",
    snippet: "The parent culture of the Hornfolke. They keep the old fires above the wall, name their daughters for storms, and bury their dead standing.",
    thumb: "../../../assets/plates/tundra.png",
    status: "draft", links: 9, edited: "3 days ago" },
  { id: "ice-jotnar", filter: "cultures", type: "Culture",
    name: "Ice Jotnar", faction: "Giants of the deep frost",
    aliases: "Hrímþursar · 'The First-Born'",
    snippet: "The eldest of the giant-kin, born of the frost in Niflheimr before the gods drew breath. They speak only in the older tongue, and only at the turning of the year.",
    thumb: "../../../assets/plates/firefalls.png",
    status: "stub", links: 18, edited: "1 week ago" },

  { id: "burning-hellas", filter: "events", type: "Event",
    name: "The Burning of Hellas", faction: "Yr 23 — Long War, third winter",
    aliases: "The Ash-Dawn",
    snippet: "The night the southern city fell to the long war. Ulf the Wolf-Father was among the dead by morning. Sigrun took the crown nine days later at Caernarfon.",
    thumb: "../../../assets/plates/hellas.png",
    status: "complete", links: 31, edited: "yesterday" },
  { id: "yggdrasil-fruit", filter: "events", type: "Event",
    name: "Yggdrasil Bears Fruit", faction: "Before-time — first dawn",
    aliases: "The Four-Worlds Dawn",
    snippet: "The great ash bore four fruits, which the gods shaped into the four Middle Earths. Ymir's blood became the seas, his hair the forests, his teeth the mountains.",
    thumb: "../../../assets/plates/forest.png",
    status: "draft", links: 28, edited: "2 days ago" },
  { id: "treaty-avalon", filter: "events", type: "Event",
    name: "The Treaty of Avalon", faction: "Yr 31 — Long War, fifth spring",
    aliases: "The Cold-Pact",
    snippet: "The pact sworn on the broken ice between Sigrun, Bran of Kernow, and the three remaining jarls. Eleven oaths, one circle of iron, no witnesses but the gulls.",
    thumb: "../../../assets/plates/avalon.png",
    status: "stub", links: 17, edited: "today" },

  { id: "drakenthar", filter: "languages", type: "Language",
    name: "Drakenthar", faction: "Tongue of dragons",
    aliases: "High Speech · Dragon-tongue",
    snippet: "The dragon-tongue, in which the speaker is assumed to be a god. There is no word for 'please' and no grammar for 'perhaps'. Three registers: high, low, and the void.",
    thumb: "../../../assets/plates/firefalls.png",
    status: "complete", links: 12, edited: "4 days ago" },
  { id: "runadhrimir", filter: "languages", type: "Language",
    name: "Runadhrimir", faction: "Old tongue of the rune-makers",
    aliases: "Rune-speech · 'The Carved Tongue'",
    snippet: "The first written speech, taught to men by Mimir at the well. Each word has a shape; each shape has a weight.",
    thumb: "../../../assets/plates/coastal.png",
    status: "draft", links: 24, edited: "today" },
  { id: "low-speech", filter: "languages", type: "Language",
    name: "Low Speech", faction: "Common tongue of Midgard",
    aliases: "Midgardr-mál · 'Hearth-Tongue'",
    snippet: "The tongue spoken in every harbour and every hall from Alba to the southern wall. Borrowed from a hundred others.",
    thumb: "../../../assets/plates/grassland.png",
    status: "stub", links: 9, edited: "1 week ago" },

  { id: "spell-still-the-tide", filter: "spells", type: "Spell",
    name: "Still the Tide", faction: "Sea-rite · taught by Njordr",
    aliases: "Sjór-stilling",
    snippet: "A nine-line incantation that lays a fjord flat for the time it takes a longship to cross. Costs the caster their voice for as many days as the crossing takes hours.",
    thumb: "../../../assets/plates/coastal.png",
    status: "draft", links: 7, edited: "today" },
  { id: "spell-name-the-bear", filter: "spells", type: "Spell",
    name: "Name the Bear", faction: "Hornfolke rune-rite",
    aliases: "Bjarn-nafn",
    snippet: "A binding that asks the bear-spirit of the high passes for safe passage. Three runes scored into birch, three drops of blood, one true name spoken aloud to the wind.",
    thumb: "../../../assets/plates/mountains.png",
    status: "stub", links: 5, edited: "yesterday" },
  { id: "spell-iron-oath", filter: "spells", type: "Spell",
    name: "The Iron Oath", faction: "Binding-rite · Iron Crown",
    aliases: "Járn-eiðr",
    snippet: "The oath that binds a jarl to the Crown. Sworn on a circle of black iron, sealed in salt, and unbreakable except by death.",
    thumb: "../../../assets/plates/hornfolke.png",
    status: "complete", links: 19, edited: "2 days ago" },

  { id: "rune-fehu", filter: "runes", type: "Rune",
    name: "Fehu — Cattle, Wealth", faction: "First of the elder row",
    aliases: "ᚠ · 'The Open Hand'",
    snippet: "The first rune. Cut into the lintel of a hall, it asks the gods to keep the herd fat and the door open.",
    thumb: "../../../assets/icons/rune.png",
    status: "draft", links: 11, edited: "3 days ago" },
  { id: "rune-isa", filter: "runes", type: "Rune",
    name: "Isa — Ice, Stillness", faction: "Eleventh of the elder row",
    aliases: "ᛁ · 'The Standing-Still'",
    snippet: "A single vertical stroke. The rune of held breath, of the frozen river, of the moment between the swing and the cut.",
    thumb: "../../../assets/icons/rune.png",
    status: "stub", links: 8, edited: "today" },
  { id: "rune-tiwaz", filter: "runes", type: "Rune",
    name: "Tiwaz — The God-Spear", faction: "Seventeenth of the elder row",
    aliases: "ᛏ · 'Tyr's Mark'",
    snippet: "The rune of victory bought with sacrifice. Cut into spear-hafts before battle. The Iron Crown carries it on its inner band.",
    thumb: "../../../assets/icons/rune.png",
    status: "complete", links: 14, edited: "yesterday" },

  { id: "iron-crown-relic", filter: "artefacts", type: "Artefact",
    name: "The Iron Crown", faction: "Relic — seat of the confederation",
    aliases: "Járnkróna · 'The Wolf-Crown'",
    snippet: "A circle of black iron, beaten cold, set with no jewel. Forged by Ulf from the prow-nails of the seven first ships. Bears the Tiwaz rune on its inner band.",
    thumb: "../../../assets/icons/artefact.png",
    status: "complete", links: 22, edited: "today" },
  { id: "wolf-banner", filter: "artefacts", type: "Artefact",
    name: "The Wolf-Banner", faction: "Standard of the Iron Crown",
    aliases: "Vargs-merki",
    snippet: "Black wolf on a field of ember-red, woven by Hilda Steel-Eye in the year of the long frost. Carried before Sigrun at every council and every crossing.",
    thumb: "../../../assets/icons/artefact.png",
    status: "draft", links: 13, edited: "4 days ago" },
  { id: "mimirs-horn", filter: "artefacts", type: "Artefact",
    name: "Mímir's Horn", faction: "Vessel · drawn from the well",
    aliases: "Gjallarhorn-bróðir · 'The Quiet Horn'",
    snippet: "The drinking-horn that Mimir keeps at the well. Whoever drinks from it tastes the water of the well — and pays the well its price.",
    thumb: "../../../assets/icons/artefact.png",
    status: "stub", links: 26, edited: "1 week ago" },
];

MM_ENTRIES.forEach(e => { e.color = MM_TYPE_COLOR[e.type] || "#d6c9a8"; });

const MM_FILTERS = [
  { id: "all",        label: "All",        color: null,      count: MM_ENTRIES.length },
  { id: "characters", label: "Characters", color: "#d99366", count: 47 },
  { id: "places",     label: "Places",     color: "#7da265", count: 23 },
  { id: "factions",   label: "Factions",   color: "#c43a4e", count: 11 },
  { id: "cultures",   label: "Cultures",   color: "#a07cc8", count: 6 },
  { id: "events",     label: "Events",     color: "#8d8478", count: 38 },
  { id: "languages",  label: "Languages",  color: "#8aa0ab", count: 4 },
  { id: "spells",     label: "Spells",     color: "#6b89c2", count: 17 },
  { id: "runes",      label: "Runes",      color: "#c9a227", count: 24 },
  { id: "artefacts",  label: "Artefacts",  color: "#a8814d", count: 19 },
];

const MM_ZONE_HEADERS = {
  all:        { eyebrow: "The library — every shelf",        title: "All entries",  sub: (n) => `${n} entries · across nine kinds` },
  characters: { eyebrow: "Chapter ii — the iron crown",      title: "Characters",   sub: (n) => `${n} entries · 6 highlighted` },
  places:     { eyebrow: "Chapter iii — the nine worlds",    title: "Places",       sub: (n) => `${n} entries · 23 in the atlas` },
  factions:   { eyebrow: "Chapter iv — banners & oaths",     title: "Factions",     sub: (n) => `${n} entries · 11 known houses` },
  cultures:   { eyebrow: "Chapter v — the peoples",          title: "Cultures",     sub: (n) => `${n} entries · 6 living, 1 lost` },
  events:     { eyebrow: "Chapter vi — the long reckoning",  title: "Events",       sub: (n) => `${n} entries · spanning four ages` },
  languages:  { eyebrow: "Chapter vii — the carved tongues", title: "Languages",    sub: (n) => `${n} entries · 4 still spoken` },
  spells:     { eyebrow: "Chapter viii — the rites",         title: "Spells",       sub: (n) => `${n} entries · 17 drafted, 4 verified` },
  runes:      { eyebrow: "Chapter ix — the elder row",       title: "Runes",        sub: (n) => `${n} entries · 24 of the elder row` },
  artefacts:  { eyebrow: "Chapter x — relics & regalia",     title: "Artefacts",    sub: (n) => `${n} entries · 19 catalogued, 3 lost` },
};

const MM_ZONE_PLATES = {
  all:        "../../../assets/plates/coastal.png",
  characters: "../../../assets/plates/kernow.png",
  places:     "../../../assets/plates/mountains.png",
  factions:   "../../../assets/plates/empire.png",
  cultures:   "../../../assets/plates/hornfolke.png",
  events:     "../../../assets/plates/hellas.png",
  languages:  "../../../assets/plates/avalon.png",
  spells:     "../../../assets/plates/firefalls.png",
  runes:      "../../../assets/plates/desert.png",
  artefacts:  "../../../assets/plates/dumnonia.png",
};

// Tools list — sidebar Tools section, plus a mobile-friendly note for each
const MM_TOOLS = [
  { id: "timeline",      label: "Timeline",        glyph: "⏳", note: "Vertical scroll · pinch-zoom era" },
  { id: "calendar",      label: "Calendar",        glyph: "◷", note: "Month view · moons + festivals" },
  { id: "tree",          label: "Family tree",     glyph: "❦", note: "Lineage list · open desktop for canvas" },
  { id: "genus",         label: "Genus tree",      glyph: "𝟁", note: "Lineage list · open desktop for canvas" },
  { id: "factiontree",   label: "Faction tree",    glyph: "⚔", note: "Banner list · open desktop for canvas" },
  { id: "relationships", label: "Connections",     glyph: "⌬", note: "Filter web · open desktop for 3D" },
  { id: "validation",    label: "Validation",      glyph: "⚖", note: "23 issues · 4 rules failing" },
  { id: "schemas",       label: "Schemas",         glyph: "▤", note: "9 built-in · 2 custom" },
  { id: "translator",    label: "Translator",      glyph: "𐌀", note: "Source → target · 4 tongues" },
  { id: "export",        label: "Export to engine", glyph: "⤓", note: "Last build · 2 mins ago" },
];

const MM_PAST_CONVOS = [
  { id: "c1", title: "Who killed Baldr?",                    when: "Just now" },
  { id: "c2", title: "The fall of Caernarfon",               when: "2h ago" },
  { id: "c3", title: "Frigg's oaths — what she missed",      when: "Yesterday" },
  { id: "c4", title: "Where the dvergr forge the seed-time", when: "3d ago" },
  { id: "c5", title: "Háloga lineage from Aud the Deep",     when: "Last week" },
];

window.MM_ENTRIES = MM_ENTRIES;
window.MM_TYPE_COLOR = MM_TYPE_COLOR;
window.MM_FILTERS = MM_FILTERS;
window.MM_ZONE_HEADERS = MM_ZONE_HEADERS;
window.MM_ZONE_PLATES = MM_ZONE_PLATES;
window.MM_TOOLS = MM_TOOLS;
window.MM_PAST_CONVOS = MM_PAST_CONVOS;
